### ISSUE TITLE
leave old images on docker hub

### ISSUE THREAD

**Issue by travisghansen** [apostvav/kannel_exporter#12]
It seems some process is removing old images from docker hub. Could you please leave the old images around?

**Comment by apostvav** [comment]
Yes you are right, I'll check it as soon as I can and I'll re-upload the images.

**Comment by travisghansen** [comment]
Thanks!

**Comment by travisghansen** [comment]
To be clear, I'm less worried about the old ones and more worried about just not doing that moving forward. It's the 2nd or 3rd time I've hit this in our prod deployments and it always causes some angst and head scratching about what is going on :)

**Comment by apostvav** [comment]
I uploaded images from 0.2.4 up to the latest. I'll keep that in mind, removing old images is unnecessary and can also cause trouble. Thanks for letting me know.

**Comment by travisghansen** [comment]
Thanks!
