### ISSUE TITLE
kannel_exporter ERROR: Authentication failed.

### ISSUE THREAD

**Issue by hamid46** [apostvav/kannel_exporter#14]
Hi Apostav,

I have successfully configured kannel exporter, but unfortunately, I am getting an error "kannel_exporter ERROR: Authentication failed." in logs.

Required details have been attached for your [references.

[status.txt](https://github.com/apostvav/kannel_exporter/files/6183458/status.txt)
<img width="629" alt="kannel_exporter" src="https://user-images.githubusercontent.com/48904279/112017311-50404a80-8b4f-11eb-834f-ed7407fc7552.png">

Thanks in advance to troubleshoot this issue.

Regards,
Hamid Mehmood

**Comment by apostvav** [comment]
Hi hamid46, sorry for the delayed response.

I have tested out the functionality of reading the pass from file and it seems to work fine. Can you run the exporter from the command line and set the target to something non existent so you'll get the url printed on your terminal?

You should see something like that

```
$ ./kannel_exporter.py --password-file /tmp/mypass --target http://127.0.0.1:50000
2021-04-24 20:31:45 kannel_exporter ERROR: Failed to open target URL: http://127.0.0.1:50000/status.xml?password=test. Error: <urlopen error [Errno 111] Connection refused>
```
Also the strip function is performed on the password ([line 360](https://github.com/apostvav/kannel_exporter/blob/9ae73990d4c6a81498864d719a5d3c5d79b3a693/kannel_exporter.py#L360)), that would be an issue in case the status password is prefixed or suffixed with whitespaces. Please check what's the password value on the urlopen to see what's the exact issue.

Thanks
