### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by Mulhem** [apostvav/kannel_exporter#15]
Thanks for the great project.
It would be great to have a sample Grafana dashboard for the exported metrics if possible.

**Comment by apostvav** [comment]
Hi, thanks for your good words. I've added a basic grafana dashboard. Hope it helps as a sample.

[kannel-grafana.json](https://github.com/apostvav/kannel_exporter/blob/master/grafana/kannel-grafana.json)
