### ISSUE TITLE
Index error when running kannel_exporter.py

### ISSUE THREAD

**Issue by jameslee007** [apostvav/kannel_exporter#2]
Hi,

  I am using Centos 7 with python 3.6 installed. I have followed the instructions you have given to run the kannel exporter. all good. But when i run the exporter it is giving the below errors.

```
[root@lee kannel_exporter-0.1]# ./kannel_exporter.py --target "http://localhost:14000" --password xyza
Traceback (most recent call last):
  File "./kannel_exporter.py", line 295, in <module>
    args.filter_smsc))
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "./kannel_exporter.py", line 73, in collect
    version = findall('svn-[a-z0-9]*', response['gateway']['version'])[0]
IndexError: list index out of range
```

 I am not a python programmer , so don't know how to solve this. I appreciate if any help you can do regrarding this.

**Comment by apostvav** [comment]
Can you provide the xml status of your kannel server (please change any information you want to hide), so I can have a look?

**Comment by jameslee007** [comment]
Thanks for the quick reply.

Here is the output of my server's xml status, when i run http://xxxx:14000/status.xml?password=xyza

Kannel bearerbox version `1.4.4'. Build `Jun 13 2018 04:21:44', compiler `4.8.5 20150623 (Red Hat 4.8.5-28)'. System Linux, release 3.10.0-693.11.6.el7.x86_64, version #1 SMP Thu Jan 4 01:06:37 UTC 2018, machine x86_64. Hostname lee, IP xxxx. Libxml version 2.9.1. Using OpenSSL 1.0.2k-fips 26 Jan 2017. Using native malloc. running, uptime 3d 2h 47m 37s 00 00 00 10 -1 0.00,0.00,0.00 0.00,0.00,0.00 1 0 0.00,0.00,0.00 0.00,0.00,0.00 0 internal smsbox BOX1 127.0.0.1 0 on-line 3d 2h 47m 28s no 1 SMPP:xxxx:2346/2346:suren1t:SMPP SMSC01 SMSC01 online 269257s 0 0 0 1 0.00,0.00,0.00 0.00,0.00,0.00 1 0 0.00,0.00,0.00 0.00,0.00,0.00

**Comment by apostvav** [comment]
OK, thanks for the feedback. I'll have a look later and I will update this issue. It looks like it fails to parse the version.

**Comment by jameslee007** [comment]
OK. Thank you. Awaiting for your reply.

**Comment by apostvav** [comment]
Hi, please check and let me know if you still have issues.

**Comment by jameslee007** [comment]
Hi,
 
Thank you very much, the Index error gone. But when i run this i am getting new error now. Please help.

  `File` "./kannel_exporter.py", line 314, in <module>
    args.filter_smsc))
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 50, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.6/site-packages/prometheus_client/core.py", line 86, in _get_names
    for metric in desc_func():
  File "./kannel_exporter.py", line 183, in collect
    box_labels = {'type':   box['type'],
TypeError: string indices must be integers

**Comment by apostvav** [comment]
OK, please provide me the xml status page so I can have a look. 
It would be really helpful if you could share the actual xml file and attach it on your response.
Remember to change any information you do not wish to share.
(maybe you should zip it first, I think only certain type of files can be attached here)
Thanks

**Comment by jameslee007** [comment]
Dear Appostvav,

Previously i was trying with **"http://X.X.X.X:14000/status.xml?password=xyza"** But the actual status page is without .xml (below)
  http://X.X.X.X:14000/status?password=xyza

The Below is the exact output of when i run  http://X.X.X.X:14000/status?password=xyza. Hope this will help you to troubleshoot .

Kannel bearerbox version `1.4.4'. Build `Jun 13 2018 04:21:44', compiler `4.8.5 20150623 (OS-Version)'. System Linux, (Kernel-Version), version #1 SMP Thu Jan 4 01:06:37 UTC 2018, machine x86_64. Hostname lee, IP X.X.X.X. Libxml version 2.9.1. Using OpenSSL 1.0.2k-fips 26 Jan 2017. Using native malloc.

Status: running, uptime 4d 0h 42m 37s

WDP: received 0 (0 queued), sent 0 (0 queued)

SMS: received 0 (0 queued), sent 1 (0 queued), store size -1
SMS: inbound (0.00,0.00,0.00) msg/sec, outbound (0.00,0.00,0.00) msg/sec

DLR: received 1, sent 0
DLR: inbound (0.00,0.00,0.00) msg/sec, outbound (0.00,0.00,0.00) msg/sec
DLR: 0 queued, using internal storage

Box connections:
    smsbox:BOX1, IP 127.0.0.1 (0 queued), (on-line 4d 0h 42m 28s) 
SMSC connections:
    SMSC01[SMSC01]    SMPP:X.X.X.X:2346/2346:suren1t:SMPP (online 348157s, rcvd: sms 0 (0.00,0.00,0.00) / dlr 1 (0.00,0.00,0.00), sent: sms 1 (0.00,0.00,0.00) / dlr 0 (0.00,0.00,0.00), failed 0, queued 0 msgs)

**Comment by apostvav** [comment]
Unfortunately I hadn't tested exporter with such a minimal setup. The problem was that the status dictionary contained an OrderedDict instead of a list of OrderedDicts when there was only one box/smsc.
Applied some changes to handle such situations. Please test again and inform me of any issues you may have so I can improve the exporter. Thank you for the feedback.

**Comment by jameslee007** [comment]
Thank you for your kind reply. I will test it and let you know.

**Comment by jameslee007** [comment]
It's working!! cheers!!

Thanks for your great help.
