### ISSUE TITLE
Could you try and please explain how the included grafana dashboard is calculating rates?

### ISSUE THREAD

**Issue by DanPhonovation** [apostvav/kannel_exporter#20]
Pardon my newness to grafana.

I'm a little confused as to what the intention of "Rates" was.

Take the first panel called "SMS Rates".

This does ` irate(bearerbox_sms_sent_total{instance="$instance"}[$__rate_interval])`.

This compares the last 2 data points in a given step and averages them out over interval?

I'm confused when i set interval to 1secs and get numbers less than 1. (Such as 0.200 which I interpret to be 2/10th of an SMS per second?).

Kannel status page totals are sky high as it keeps them for life of the kannel instance, so maybe this is throwing it off?

Example of one of my scrape configs:

```
__address__="kannel-exporter-108dot221-port-21000:9390"
__metrics_path__="/"
__scheme__="http"
__scrape_interval__="5s"
__scrape_timeout__="5s"
instance="SMPP Client-108.221:21000"
job="kannel-exporters"
```

Edit: changed __scrape_interval__ in prometheus to 1s. Seems better.

**Comment by apostvav** [comment]
The rate functions are used on counters to see how fast they're going up. You can check this robustperception [blog post](https://www.robustperception.io/avoid-irate-in-alerts) and the prometheus documentation for more details.

Another thing you should be aware of is that you should avoid using too small intervals, for example 1". Begin with something longer, eg 5 minutes. There should be a few samples in the interval you define. If you define 1" and the Prometheus check interval is 15" then the results would not make sense.

**Comment by DanPhonovation** [comment]
Thanks for answer.  I'll admit,  I'm confused but will try to read up more on your comments
